### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-blobs#1]
I've gotten this a few times in the Patchwork command line while running Patchbay. Sbot fails and this is the error:

```
TypeError: Cannot read property 'push' of undefined
    at /home/ev/builds/patchwork/node_modules/ssb-blobs/inject.js:163:50
    at next (/home/ev/builds/patchwork/node_modules/ssb-blobs/inject.js:115:7)
    at /home/ev/builds/patchwork/node_modules/ssb-blobs/inject.js:104:13
    at /home/ev/builds/patchwork/node_modules/multiblob/index.js:141:15
    at continuation (/home/ev/builds/patchwork/node_modules/continuable-list/index.js:24:25)
    at /home/ev/builds/patchwork/node_modules/multiblob/index.js:122:9
    at done (/home/ev/builds/patchwork/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by mmckegg** [comment]
Fixed in 05e61fd5fad29a4bf0301ad0b2907993b0cb7575 (v0.1.7). This can probably be closed now.
